### ISSUE TITLE
windows v1.0.1

### ISSUE THREAD

**Issue by CaptainSkywave** [overhold-org/Overhold-Wallet#12]
Opened the wallet with the .exe inside the unpacked folder.
Enter the 12 word mnemonic under Recovery - wallet opens - and I then sign out.
Log in with the username and password belonging to that 12 word account says Username was not found in the database.
Do we need to copy anything from the v1.0.0 folder and paste it into the v1.0.1 folder - eg. private.js or db.js?

**Comment by blag0j** [comment]
@CaptainSkywave there isn't specific username and password belonging to the mnemonic, those are separate data. If you've recovered from mnemonic, independent on the wallet version your username is `username` and your password is `password`. You will have to change it at the settings page.

The username and password are stored only locally, and are for additional security in case multiple users are using the same machine.
