### ISSUE TITLE
Tab 'Backup Wallet' Spelling Mistake

### ISSUE THREAD

**Issue by AwesomeVinc** [overhold-org/Overhold-Wallet#17]
![image](https://user-images.githubusercontent.com/31467087/48551336-1b49da80-e93a-11e8-869c-32f567f4f05d.png)

Spelling mistake in the foot note. I believe it should say 'Fire' instead of 'Filre'.

**Comment by blag0j** [comment]
@AwesomeVinc you're right it should say 'fire' instead of 'filre'.

**Comment by blag0j** [comment]
@AwesomeVinc This issue has been fixed with the latest updates in the develop branch. The release will be published in the following days.
