### ISSUE TITLE
Unable to see 12 word back up words after clicking "Show phrase" windows

### ISSUE THREAD

**Issue by rambogoham** [overhold-org/Overhold-Wallet#25]
**Describe the bug**
Unable to see 12 word back up words after clicking "Show phrase" windows

**To Reproduce**
1. Go to "backup Wallet"
2. Click on "show phrase"
3. See error, doesn't load
4. This is on windows download

**Expected behavior**
My 12 word seed phrase

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Running mode (normal user)

**Additional context**
Takes quite a while to have overhold wallet login pop up after clicking the wallet. This is after clicking extract all and saving the wallet to a desktop folder.

**Comment by blag0j** [comment]
@rambogoham thanks for the report. I've just tried to reproduce the bug on new Windows 10 installation using the 1.1.0 wallet version, but I could not reproduce it. About the slow loading, that is not present in the newest release. Are you sure you're running the latest version (1.1.0) which includes the faster loading and also the database reload fix? 

From the additional context and from the fact that we couldn't reproduce the reported bug on the newest version on the same operating system as reported, I assume that you're running some of the previous releases. 

Please check that the version you're installing is correct and let us know if the issue still persists. Also, you don't need to extract anything. You need only to download the file named 'Overhold-1.1.0-win.exe
' from the [v1.1.0 release page](https://github.com/overhold-org/Overhold-Wallet/releases/tag/1.1.0), and install it. After the application is installed it will be launched immediately and shortcut for the application will be added on Desktop.

**Comment by rambogoham** [comment]
Yep, was running an earlier version. Everything works very well now.
