### ISSUE TITLE
Creating New Account or Recovery, Log In - do not work

### ISSUE THREAD

**Issue by bolecoin** [overhold-org/Overhold-Wallet#3]
Using Windows 10 Pro with the executable from the win-unpacked folder (the other one does not even create a window).
Tried to run both as admin, but that did not help.

When trying to create a new account:
After filling out the desired username and 2x password and clicking on Register, I get a warning, that there already is a user registered. This also happened the first time I tried it. I did not use the NVO wallet on this computer previously. After clicking on Proceed, the Register button turns grey and nothing else happens. When trying to log in with the defined username and password, the Log in button turns grey and nothing happens.

When trying to use Recovery with 12 word phrase extracted from NVO wallet:
Same warning, that a user is already registered. After clicking Proceed, nothing happens. The Recovery button stays blue. When trying to login with 'username' as Username and 'password' as Password, the Log in button turns grey and nothing happens.

**Comment by blag0j** [comment]
@bolecoin thanks for the detailed explanation. It looks like there is an issue with creating the local databases required for the application to run properly. We will take a further look into the issue and we will also try to find the problem and fix it as soon as possible.

It would be helpful if you can provide us with the build version of your OS, and also if you are using single or multi-user system.

**Comment by bolecoin** [comment]
I am using Windows 10 Pro / Version 1809 (Build 17763.55) and I am the only user.

**Comment by blag0j** [comment]
@bolecoin Thank you, we will provide you with more details as soon as possible.

**Comment by blag0j** [comment]
@bolecoin the details help us a lot, thank you. Currently we're packaging the windows application as a portable version, not as installer, that's why it takes so long for it to run - it will be optimized.

There are apparently issues with specific versions of the Windows OS at the database creation/loading procedure. We will try to get this fixed as soon as possible and release fixed version.

**Comment by blag0j** [comment]
@bolecoin Please checkout the latest release, it contains the fixed version of the wallet which covers this bug as well.

I am closing this issue, if the same error persist with the new release at your side, please re-open it.

**Comment by bolecoin** [comment]
I can confirm, that the packed version now works as intended (besides the 100-110 seconds delay), however the bug of the unpacked version mentioned in my original post still persists.
